baseurl = "https://picymru.org.uk/"
languageCode = "en-gb"
title = "PiCymru"
theme = "picymru"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "PiCymru"